import "@altea/altea/server/dynamicQuery/fluentIncludeQuery"; // FluentInclude.withQuery
import "@altea/altea/server"; // installs save()/toLite()
import type { SchemaBuilder } from "@altea/altea/server/schema";
import { Schema } from "@altea/altea/server/schema";
import type { Table } from "@altea/altea/server/schema/table";
import { Connector } from "@altea/altea/server/connection/connector";
import { Transaction } from "@altea/altea/server/connection/transaction";
import { Administrator } from "@altea/altea/server/Administrator";
import { table } from "@altea/altea/server/table";
import { ExecutionMode } from "@altea/altea/server/executionMode";
import { ExceptionLogic } from "@altea/altea/server/exceptionLogic";
import { QueryLogic } from "@altea/altea/server/dynamicQuery/queryLogic";
import { Clock } from "@altea/altea/data/utils/clock";
import { Entity, type Type } from "@altea/altea/data/entity";
import { SqlMigrationEntity, TypeScriptMigrationEntity, LoadMethodLogEntity, MigrationMessage } from "../data/Migrations";
import { SafeConsole, Color } from "./SafeConsole";

// The module starter plus the two helpers both runners and the app's loaders use: `ensureMigrationTable`
// (create the history table on the fly) and `executeLoadProcess` (run one load step, logged to
// LoadMethodLogEntity with its exception).
//
// `executeLoadProcess` RETURNS the caught error rather than throwing, so a caller can decide whether the
// remaining steps still run.
//
// Port of Signum.Migrations' MigrationLogic.cs — see port/Migrations.md.

export namespace MigrationLogic {

    export function start(sb: SchemaBuilder): void {
        if (sb.alreadyDefined(start))
            return;

        sb.include(SqlMigrationEntity).withQuery();
        sb.include(TypeScriptMigrationEntity).withQuery();
        sb.include(LoadMethodLogEntity).withQuery();

        // Signum's `Duration` column on the load log (one of MigrationLogic's own default columns there).
        // Signum gets the token from the `[ExpressionField]` property; altea registers it, because a
        // `@quoted` method is not a member of the type as far as the query metadata is concerned. The
        // caption is a MESSAGE and not `nicePropertyName(l => l.durationMilliseconds())`, which resolves
        // under (declaring type, member) and would humanise — a quoted method has no <Member> entry.
        QueryLogic.expressions.register(LoadMethodLogEntity, l => l.durationMilliseconds(),
            MigrationMessage.Duration);

        void ExceptionLogic;
    }

    /**
     * The history table has to exist BEFORE the first migration runs —
     * and it cannot itself be created by a migration — so it is created on the fly, with its indexes, the
     * first time a runner needs it.
     */
    export async function ensureMigrationTable<T extends Entity>(type: Type<T>): Promise<void> {
        await Transaction.create(async () => {
            const connector = Connector.current();
            const table = connector.schema.table(type as Type<Entity>);

            if (await Administrator.existsTable(table))
                return;

            const sqlBuilder = connector.sqlBuilder;

            // Also create the SCHEMA when the table lives outside the default one. `createSchema` is
            // idempotent-guarded by the dialect builder, so it is safe to emit unconditionally.
            if (table.name.schema.name !== "")
                await sqlBuilder.createSchema(table.name.schema).executeNonQuery();

            await sqlBuilder.createTableSql(table).executeNonQuery();

            for (const index of table.indexes)
                await sqlBuilder.createIndex(index).executeNonQuery();

            SafeConsole.writeLineColor(Color.white,
                MigrationMessage.Table0AutoGenerated.niceToString(table.name.toString()));
        });
    }

    /** Are there applied SQL migrations in this database? */
    export async function sqlMigrationCount(): Promise<number> {
        const table = Connector.current().schema.tryTable(SqlMigrationEntity);
        if (table == null || !await Administrator.existsTable(table))
            return 0;
        return (await tableRows(SqlMigrationEntity)).length;
    }

    /**
     * Run one load step inside a banner, LOG it to
     * LoadMethodLogEntity (start / end / exception), and return the error instead of throwing so the caller
     * can decide whether the remaining steps still run.
     *
     * The log row is skipped when the table is not part of this schema, so an app that does not start
     * MigrationLogic still gets the banner and the timing.
     */
    export async function executeLoadProcess(action: () => Promise<void>, description: string, className?: string): Promise<unknown> {
        SafeConsole.banner(`Executing ${description}`);

        const hasLog = Schema.current.tryTable(LoadMethodLogEntity) != null;
        const log = !hasLog ? null : LoadMethodLogEntity.create({
            start: Clock.now,
            className: className ?? null,
            methodName: description,
            description,
        });
        if (log != null)
            await log.save();

        const startedAt = Date.now();
        try {
            await action();
            if (log != null) {
                log.end = Clock.now;
                await log.save();
            }
            SafeConsole.banner(`Executed ${description} (took ${Date.now() - startedAt} ms)`);
            return null;
        } catch (e) {
            SafeConsole.writeLine();
            SafeConsole.writeLineColor(Color.red, `${(e as Error)?.name ?? "Error"}: ${(e as Error)?.message ?? String(e)}`);
            SafeConsole.writeLineColor(Color.darkRed, (e as Error)?.stack ?? "(no stack trace)");

            if (log != null) {
                // The exception log is written in its OWN transaction (ExceptionLogic does this
                // internally): the failing step may have poisoned the ambient one.
                const exception = await ExceptionLogic.logException(e);
                log.exception = exception?.toLite() ?? null;
                log.end = Clock.now;
                try { await log.save(); } catch { /* the ambient transaction is already rolled back */ }
            }
            return e;
        }
    }
}

// A tiny local helper: read a whole migration table ungated. (There is no import cycle to dodge here —
// `Administrator` above already pulls both of these in statically.)
async function tableRows<T extends Entity>(type: Type<T>): Promise<T[]> {
    return await ExecutionMode.global(() => table(type as Type<Entity>).toArray()) as T[];
}

export type { Table };
