import { reflect } from "@altea/altea/data/reflection";
import { Entity } from "@altea/altea/data/entity";
import { Lite } from "@altea/altea/data/lite";
import { entity, uniqueIndex, stringLengthValidator, quoted } from "@altea/altea/data/decorators";
import { Temporal } from "@altea/altea/data/basics";
import { msg } from "@altea/altea/data/utils/localization";
import { ExceptionEntity } from "@altea/altea/data/exception";

// Port of Signum.Migrations' entity model (SqlMigration.cs + CSharpMigration.cs + LoadMethodLogEntity.cs).
// Three System/Transactional tables, all `TicksColumn(false)` — history rows nobody concurrently edits:
//  • SqlMigrationEntity     — one row per APPLIED .sql migration file, keyed by its version stamp.
//  • CSharpMigrationEntity  — one row per executed code migration, keyed by its unique name.
//  • LoadMethodLogEntity    — one row per `executeLoadProcess` run: what ran, how long, and what it threw.
//
// altea divergences:
//  - `DateTime` → `Temporal.PlainDateTime` (the terminal's wall clock, like the scheduler's rules).
//  - Signum's `Duration` is an [ExpressionField] (a query column); here it is an in-memory helper, matching
//    what @altea/altea-processes and @altea/altea-scheduler already do for their own log durations.

@reflect
@entity("System", "Transactional")
export class SqlMigrationEntity extends Entity {
    @uniqueIndex
    @stringLengthValidator({ max: 200 })
    versionNumber: string;

    @stringLengthValidator({ min: 0, max: 400 })
    comment: string | null;

    @quoted toString(): string { return this.versionNumber; }
}

@reflect
@entity("System", "Transactional")
export class CSharpMigrationEntity extends Entity {
    @uniqueIndex
    @stringLengthValidator({ max: 200 })
    uniqueName: string;

    executionDate: Temporal.PlainDateTime;

    @quoted toString(): string { return this.uniqueName; }
}

@reflect
@entity("System", "Transactional")
export class LoadMethodLogEntity extends Entity {
    @stringLengthValidator({ min: 3, max: 400 })
    methodName: string | null;

    @stringLengthValidator({ min: 3, max: 400 })
    className: string | null;

    @stringLengthValidator({ min: 3, max: 400 })
    description: string | null;

    start: Temporal.PlainDateTime;

    end: Temporal.PlainDateTime | null;

    exception: Lite<ExceptionEntity> | null;

    /**
     * Signum's `Duration` ([ExpressionField] over `(End - Start).TotalMilliseconds`) — an IN-MEMORY helper
     * here, not a query column, matching the same decision in @altea/altea-processes (Process.
     * durationMilliseconds) and @altea/altea-scheduler (ScheduledTaskLog): the value is only ever read off a
     * loaded row, and a stored `start`/`end` pair is what a query filters on.
     */
    duration(): number | null {
        return this.end == null ? null : this.end.since(this.start).total({ unit: "milliseconds" });
    }

    @quoted toString(): string { return this.methodName ?? ""; }
}

// Signum's MigrationMessage (Signum.Migrations' Translations). Only the strings the runners actually print
// are declared; the console UI of the two runners is otherwise plain (Signum's own prompts are hard-coded
// English inside SafeConsole calls).
export const MigrationMessage = {
    ReadingCSharpMigrations: msg(),
    AllMigrationsAreExecuted: msg(),
    RunMigrations0: msg(),
    ReadingMigrationsFrom0: msg(),
    CreateNewMigration: msg(),
    NoChangesFound: msg(),
    SomeChangesFoundHereIsTheScript: msg(),
    CommentForTheNewMigration: msg(),
    Run0Migrations: msg(),
    ThereAreFreshExecutedMigrationsThatAreNotInTheFolderGetLatestVersion: msg(),
    PossibleMergeConflictThereAreOldMigrationsInTheFolderThatHaveNotBeenExecuted: msg(),
    Table0AutoGenerated: msg(),
    Directory0AutoGenerated: msg(),
};
