import "@altea/altea/server";
import "@altea/altea/server/dynamicQuery/fluentIncludeQuery"; // FluentInclude.withQuery
import "@altea/altea/server/fluentOperations"; // FluentInclude.withSave / withDelete
import { randomBytes } from "node:crypto";
import { SchemaBuilder } from "@altea/altea/server/schema";
import { table } from "@altea/altea/server/table";
import type { ResetLazy } from "@altea/altea/data/resetLazy";
import { RestApiKeyEntity, RestApiKeyOperation } from "../data/Rest";

// Port of Signum.Rest's RestApiKeyLogic.cs — the key table plus the process-wide cache the authenticator
// reads on every request.
//
// altea divergences:
//  - **the cache is ASYNC.** `sb.globalLazy` returns a `ResetLazy<T>` holding the resolved value (altea has
//    no synchronous DB access), so the authenticator awaits it. That is fine: the authenticator chain is
//    already async. Signum's `FrozenDictionary` becomes a plain Map — nothing here mutates it.
//  - **`WebEncoders.Base64UrlEncode` → `randomBytes(32).toString("base64url")`**, the same 32 random bytes
//    in the same alphabet, so a key generated by either framework is indistinguishable.
export namespace RestApiKeyLogic {

    /** Signum's `ApiKeyQueryParameter` / `ApiKeyHeader` — a caller may pass the key either way. */
    export const apiKeyQueryParameter = "apiKey";
    export const apiKeyHeader = "X-ApiKey";

    /** apiKey → the row. Reset whenever a RestApiKey is saved, deleted or touched by set-based DML. */
    export let restApiKeyCache: ResetLazy<Map<string, RestApiKeyEntity>> = undefined!;

    /** Overridable, exactly as Signum's `GenerateRestApiKey` func is. */
    export let generateRestApiKey: () => string = defaultGenerateRestApiKey;

    let started = false;

    export function start(sb: SchemaBuilder): void {
        if (started)
            return;
        started = true;

        sb.include(RestApiKeyEntity)
            .withSave(RestApiKeyOperation.Save)
            .withDelete(RestApiKeyOperation.Delete)
            .withQuery();

        restApiKeyCache = sb.globalLazy(
            async () => new Map((await table(RestApiKeyEntity).toArray()).map(k => [k.apiKey, k])),
            { invalidateWith: [RestApiKeyEntity] });
    }

    /** Signum's `DefaultGenerateRestApiKey`: 32 cryptographically random bytes, base64url-encoded. */
    function defaultGenerateRestApiKey(): string {
        return randomBytes(32).toString("base64url");
    }

    /** The key belonging to a user, if any — what the client's "open Swagger / MCP with my key" needs. */
    export async function apiKeyOf(userId: RestApiKeyEntity["user"]["id"]): Promise<string | null> {
        const found = await table(RestApiKeyEntity).filter(k => k.user.id == userId).toArray();
        return found.length === 0 ? null : found[0]!.apiKey;
    }
}
