// The DynamicQuery enums (Signum's Signum.DynamicQuery.cs — a C#-autogenerated file in Signum, so
// NOT ported verbatim; these live here as real altea enums in the entities layer). They are the
// query-layer vocabulary shared by the client (Finder / SearchControl) and the server (query
// controller): filter operations/types, ordering, pagination, system-time, etc.
//
// Representation: STRING-VALUED enums — the value IS the wire discriminator (e.g. FilterOperation.
// IsIn === "IsIn"), so they round-trip through altea/json as their member name AND the ported
// query code that compares against string literals keeps working. Use the enum members
// (FilterOperation.IsIn) in new code; the string form is what crosses the wire.

import { msg } from './utils/localization';

// Query-token display messages (Signum's Signum.DynamicQuery.Tokens QueryTokenMessage /
// QueryTokenDateMessage, and Signum.External CollectionMessage — all C#-autogenerated resx there,
// here real altea LocalizableMessage containers). Used by QueryToken.getNiceTypeName / completeToken
// to name synthetic tokens; the display text arrives via the reflection translation blob (msg()'s
// name-inferred default is the fallback).
export const QueryTokenMessage = {
    AnyEntity: msg(),
    CellOperation: msg(),
    Check: msg(),
    ContainerOfCellOperations: msg(),
    DateTime: msg(),
    DecimalNumber: msg(),
    GlobalUniqueIdentifier: msg(),
    IndexerContainer: msg(),
    ListOf0: msg("List of {0}"),
    Number: msg(),
    Text: msg(),
};

export const QueryTokenDateMessage = {
    Date: msg(),
    TimeOfDay: msg(),
};

export const CollectionMessage = {
    Or: msg(),
};

export enum ColumnOptionsMode {
    Add = "Add",
    Remove = "Remove",
    ReplaceAll = "ReplaceAll",
    InsertStart = "InsertStart",
    ReplaceOrAdd = "ReplaceOrAdd",
}

export enum CombineRows {
    EqualValue = "EqualValue",
    EqualEntity = "EqualEntity",
}

export enum DashboardBehaviour {
    PromoteToDasboardPinnedFilter = "PromoteToDasboardPinnedFilter",
    UseAsInitialSelection = "UseAsInitialSelection",
    UseWhenNoFilters = "UseWhenNoFilters",
}

export enum FilterGroupOperation {
    And = "And",
    Or = "Or",
}

export enum FilterOperation {
    EqualTo = "EqualTo",
    DistinctTo = "DistinctTo",
    GreaterThan = "GreaterThan",
    GreaterThanOrEqual = "GreaterThanOrEqual",
    LessThan = "LessThan",
    LessThanOrEqual = "LessThanOrEqual",
    Contains = "Contains",
    StartsWith = "StartsWith",
    EndsWith = "EndsWith",
    Like = "Like",
    NotContains = "NotContains",
    NotStartsWith = "NotStartsWith",
    NotEndsWith = "NotEndsWith",
    NotLike = "NotLike",
    IsIn = "IsIn",
    IsNotIn = "IsNotIn",
    ComplexCondition = "ComplexCondition",
    FreeText = "FreeText",
    TsQuery = "TsQuery",
    TsQuery_Plain = "TsQuery_Plain",
    TsQuery_Phrase = "TsQuery_Phrase",
    TsQuery_WebSearch = "TsQuery_WebSearch",
    SmartSearch = "SmartSearch",
    Between = "Between",
    BetweenNoEnd = "BetweenNoEnd",
}

export enum FilterType {
    Integer = "Integer",
    Decimal = "Decimal",
    String = "String",
    DateTime = "DateTime",
    Time = "Time",
    Lite = "Lite",
    Embedded = "Embedded",
    Model = "Model",
    Boolean = "Boolean",
    Enum = "Enum",
    Guid = "Guid",
    TsVector = "TsVector",
    Vector = "Vector",
}

export enum OrderType {
    Ascending = "Ascending",
    Descending = "Descending",
}

export enum PaginationMode {
    All = "All",
    Firsts = "Firsts",
    Paginate = "Paginate",
}

export enum PinnedFilterActive {
    Always = "Always",
    WhenHasValue = "WhenHasValue",
    Checkbox_Checked = "Checkbox_Checked",
    Checkbox_Unchecked = "Checkbox_Unchecked",
    NotCheckbox_Checked = "NotCheckbox_Checked",
    NotCheckbox_Unchecked = "NotCheckbox_Unchecked",
}

export enum RefreshMode {
    Auto = "Auto",
    Manual = "Manual",
}

export enum SystemTimeJoinMode {
    Current = "Current",
    FirstCompatible = "FirstCompatible",
    AllCompatible = "AllCompatible",
}

export enum SystemTimeMode {
    AsOf = "AsOf",
    Between = "Between",
    ContainedIn = "ContainedIn",
    All = "All",
    TimeSeries = "TimeSeries",
}

export enum TimeSeriesUnit {
    Year = "Year",
    Quarter = "Quarter",
    Month = "Month",
    Week = "Week",
    Day = "Day",
    Hour = "Hour",
    Minute = "Minute",
    Second = "Second",
    Millisecond = "Millisecond",
}

export enum UniqueType {
    First = "First",
    FirstOrDefault = "FirstOrDefault",
    Single = "Single",
    SingleOrDefault = "SingleOrDefault",
    Only = "Only",
}
