// Client UI message containers (Signum's Signum.Entities EntityControlMessage / SelectorMessage /
// JavascriptMessage / SearchMessage — C#-autogenerated there, real altea LocalizableMessage
// containers here). Only the members the ported Lines / SelectorModal / Constructor use so far; add
// more as further components land. Display text arrives via the reflection translation blob; the
// msg() name-inferred / explicit default is the fallback.
import { msg } from './utils/localization';

export const EntityControlMessage = {
    Add: msg("Add"),
    Create: msg(),
    Find: msg(),
    Paste: msg(),
    Remove: msg(),
    View: msg(),
    MoveUp: msg("Move up"),
    MoveDown: msg("Move down"),
    MoveRight: msg("Move right"),
    MoveLeft: msg("Move left"),
    MoveWithDragAndDropOrCtrlUpDown: msg("Move (with drag and drop or Ctrl + Up / Down)"),
    MoveWithDragAndDropOrCtrlLeftRight: msg("Move (with drag and drop or Ctrl + Left / Right)"),
    Close: msg("Close"),
    Reload: msg("Reload"),
    Changed: msg("Changed"),
    NoChanges: msg("No changes"),
};

export const JavascriptMessage = {
    ok: msg("OK"),
    cancel: msg("Cancel"),
    yes: msg("Yes"),
    no: msg("No"),
    executed: msg("Executed"),
    error: msg("Error"),
    Close: msg("Close"),
    loading: msg("Loading…"),
    Date: msg("Date"),
    Selected: msg("Selected"),
    addFilter: msg("Add filter"),
    editColumn: msg("Edit column"),
    groupByThisColumn: msg("Group by this column"),
    insertColumn: msg("Insert column"),
    noActionsFound: msg("No actions found"),
    removeColumn: msg("Remove column"),
    removeOtherColumns: msg("Remove other columns"),
    restoreDefaultColumns: msg("Restore default columns"),
    searchForResults: msg("Search for results"),
    ShowGroup: msg("Show group"),
    loseCurrentChanges: msg("There are changes in the current entity without saving. Do you want to lose them?"),
    saveChangesBeforeOrPressCancel: msg("Save changes before or press cancel"),
};

export const FrameMessage = {
    Fullscreen: msg("Fullscreen"),
    ThereAreErrors: msg("There are errors"),
    Main: msg("Main"),
};

// SaveChanges (Signum's SaveChangesMessage) — the lose-changes modal.
export const SaveChangesMessage = {
    ThereAreChanges: msg("There are changes"),
    YoureTryingToCloseAnEntityWithChanges: msg("You're trying to close an entity with changes. What do you want to do?"),
    LoseChanges: msg("Lose changes"),
};

export const SearchMessage = {
    Operations: msg("Operations"),
    Search: msg("Search"),
    View: msg("View"),
    CreateNew0_G: msg("Create new {0}"),
    AddValue: msg("Add value"),
    DeleteFilter: msg("Delete filter"),
    DeleteAllFilter: msg("Delete all filters"),
    Field: msg("Field"),
    Operator: msg("Operator"),
    Value: msg("Value"),
    Label: msg("Label"),
    Column: msg("Column"),
    ColSpan: msg("Col span"),
    Row: msg("Row"),
    IsActive: msg("Is active"),
    Split: msg("Split"),
    AddFilter: msg("Add filter"),
    AddOrGroup: msg("Add OR group"),
    AddAndGroup: msg("Add AND group"),
    EditPinnedFilters: msg("Edit pinned filters"),
    OrGroup: msg("Or Group"),
    AndGroup: msg("And Group"),
    PinFilter: msg("Pin filter"),
    UnpinFilter: msg("Unpin filter"),
    ParentValue: msg("Parent value"),
    Enter: msg("Enter"),
    SplitsTheValuesAndSearchesEachOneIndependentlyInAnANDGroup: msg("Splits the values and searches each one independently in an AND group"),
    SplitsTheStringValueBySpaceAndSearchesEachPartIndependentlyInAnANDGroup: msg("Splits the string value by space and searches each part independently in an AND group"),
    // Pagination
    _0Results_N: msg("{0} results"),
    First0Results_N: msg("First {0} results"),
    NoResultsInThisPage: msg("No results in this page"),
    _01of2Results_N: msg("{0} - {1} of {2} results"),
    PaginationAll_0Elements: msg("Show {0} elements"),
    PaginationFirst_01Elements: msg("Show first {0} of {1} elements"),
    PaginationPages_0Of01lements: msg("Show pages {0} of {1} elements"),
    PaginationMode: msg("Pagination mode"),
    NumberOfElementsForPagination: msg("Number of elements per page"),
    // Column editor
    ColumnField: msg("Field"),
    ShowMore: msg("Show more"),
    SummaryHeader: msg("Summary header"),
    DisplayName: msg("Display name"),
    CombineRowsWith: msg("Combine rows with"),
    Equal0: msg("Equal {0}"),
    InvalidColumnExpression: msg("Invalid column expression"),
    CollectionsCanNotBeAddedAsColumns: msg("Collections can not be added as columns"),
    SummaryHeaderMustBeAnAggregate: msg("Summary header must be an aggregate"),
    // SearchControlLoaded toolbar / results / context menu
    AdvancedFilters: msg("Advanced filters"),
    After: msg("After"),
    AllPages: msg("All pages"),
    Before: msg("Before"),
    Columns: msg("Columns"),
    Copy: msg("Copy"),
    CurrentPage: msg("Current page"),
    DerivedGroupKey: msg("Derived group key"),
    EditAllColumns: msg("Edit all columns"),
    FilterDesigner: msg("Filter designer"),
    FilterMenu: msg("Filter menu"),
    FilterTypeSelection: msg("Select filter type"),
    Filters: msg("Filters"),
    GoBackToPageOne: msg("Go back to page one"),
    GroupKey: msg("Group key"),
    HideHiddenColumns: msg("Hide hidden columns"),
    MoreThanOne0Selected: msg("More than one {0} selected"),
    NoResultsFound: msg("No results found"),
    NoResultsFoundInPage01: msg("No results found in page {0} of {1}"),
    OperationsForSelectedElements: msg("Operations for selected elements"),
    Refresh: msg("Refresh"),
    SelectAllResults: msg("Select all results"),
    ShowHiddenColumns: msg("Show hidden columns"),
    SimpleFilters: msg("Simple filters"),
    SwitchViewMode: msg("Switch view mode"),
    TimeMachine: msg("Time machine"),
    ToPreventPerformanceIssuesAutomaticSearchIsDisabledCheckYourFiltersAndThenClickSearchButton: msg("To prevent performance issues automatic search is disabled. Check your filters and then click the search button"),
    YouHaveSelectedAllRowsOnThisPageDoYouWantTo0OnlyTheseRowsOrToAllRowsAcrossAllPages: msg("You have selected all rows on this page. Do you want to {0} only these rows or all rows across all pages?"),
    _0GroupWith1_N: msg("{0} group with {1}"),
    _0ResultTable: msg("{0} result table"),
    // SearchModal
    ReturnNewEntity: msg("Return new entity"),
    DoYouWantToSelectTheNew01_G: msg("Do you want to select the new {0} {1}?"),
    PleaseSelectOneOrMore0_G: msg("Please select one or more {0}"),
    PleaseSelectOneOrSeveralEntities: msg("Please select one or several entities"),
    PleaseSelectA0_G: msg("Please select a {0}"),
    PleaseSelectAnEntity: msg("Please select an entity"),
};

export const SelectorMessage = {
    ChooseAValue: msg("Choose a value"),
    ChooseValues: msg("Choose values"),
    PleaseChooseA0ToContinue: msg("Please choose a {0} to continue"),
    PleaseChooseAValueToContinue: msg("Please choose a value to continue"),
    PleaseSelectAConstructor: msg("Please select a constructor"),
    PleaseSelectAType: msg("Please select a type"),
    PleaseSelectAtLeastOneValueToContinue: msg("Please select at least one value to continue"),
    TypeSelector: msg("Type selector"),
    _0Selector: msg("{0} selector"),
};

// Operations (Signum's OperationMessage). Members used by the Operations client layer.
export const OperationMessage = {
    Create: msg("Create…"),
    // Simplifies a ConstructorFrom nice name inside a Create group ("Create Order from Customer" → group 1).
    CreateFromRegex: msg("^Create (.+?)( from .+)?$"),
    Create0: msg("Create {0}"),
    Confirm: msg("Confirm"),
    PleaseConfirmYouWouldLikeToDelete0FromTheSystem: msg("Please confirm that you would like to delete {0} from the system"),
    As: msg("as"),
    PleaseConfirmYouWouldLikeTo01: msg("Please confirm you would like to {0} {1}"),
    _0AndClose: msg("{0} and close"),
    _0AndNew: msg("{0} and new"),
    MultiSetter: msg("(Multi setter)"),
    Executing0: msg("Executing {0}"),
    Deleting: msg("Deleting…"),
    _0Errors: msg("{0} errors"),
    CancelOperation: msg("Cancel operation"),
    AreYouSureYouWantToCancelTheOperation: msg("Are you sure you want to cancel the operation?"),
    ClosingThisModalOrBrowserTabWillCancelTheOperation: msg("Closing this modal or browser tab will cancel the operation"),
    PleaseConfirmThatYouWouldLikeToApplyTheAboveChangesAndExecute0Over12: msg("Please confirm that you would like to apply the above changes and execute {0} over {1} {2}"),
};

// Engine (Signum's EngineMessage) — the members the Operations layer reads.
export const EngineMessage = {
    TheEntity0IsNew: msg("The entity {0} is new"),
};

// NormalControl (Signum's NormalControlMessage) — the members the Operations layer reads.
export const NormalControlMessage = {
    SaveChangesFirst: msg("Save changes first!"),
};

// Connection (Signum's ConnectionMessage) — used by ErrorModal.
export const ConnectionMessage = {
    VersionInfo: msg("Version info"),
    ANewVersionHasJustBeenDeployedSaveChangesAnd0: msg("A new version has just been deployed! Save changes and {0}"),
    OutdatedClientApplication: msg("This application has been updated, please refresh the page!"),
    ANewVersionHasJustBeenDeployedConsiderReload: msg("A new version has just been deployed! Consider reloading the page."),
    Refresh: msg("Refresh"),
};

// CascadeDelete (Signum's CascadeDeleteMessage) — used by DeleteErrorModal.
export const CascadeDeleteMessage = {
    ThisEntityIsStillReferenced: msg("This entity is still referenced"),
    TheFollowingEntitiesStillReference0RemoveThemBeforeDeleting: msg("The following entities still reference {0}. Remove them before deleting."),
    NoReferencesFoundYouCanNowDeleteThisEntity: msg("No references found. You can now delete this entity."),
    Refresh: msg("Refresh"),
    ReferencedVia: msg("Referenced via"),
    Delete: msg("Delete"),
    ErrorDetails: msg("Error details"),
    _0MoreNotVisibleForYou: msg("{0} more not visible for you"),
};
