// Client UI message containers (Signum's Signum.Entities EntityControlMessage / SelectorMessage /
// JavascriptMessage / SearchMessage — C#-autogenerated there, real altea LocalizableMessage
// containers here). Only the members the ported Lines / SelectorModal / Constructor use so far; add
// more as further components land. Display text arrives via the reflection translation blob; the
// msg() name-inferred / explicit default is the fallback.
import { msg } from './utils/localization';

export const EntityControlMessage = {
    Create: msg(),
    Find: msg(),
    Paste: msg(),
    Remove: msg(),
    View: msg(),
};

export const JavascriptMessage = {
    ok: msg("OK"),
    loading: msg("Loading…"),
    Date: msg("Date"),
};

export const SearchMessage = {
    Search: msg("Search"),
    CreateNew0_G: msg("Create new {0}"),
};

export const SelectorMessage = {
    ChooseAValue: msg("Choose a value"),
    ChooseValues: msg("Choose values"),
    PleaseChooseA0ToContinue: msg("Please choose a {0} to continue"),
    PleaseChooseAValueToContinue: msg("Please choose a value to continue"),
    PleaseSelectAConstructor: msg("Please select a constructor"),
    PleaseSelectAType: msg("Please select a type"),
    PleaseSelectAtLeastOneValueToContinue: msg("Please select at least one value to continue"),
    TypeSelector: msg("Type selector"),
    _0Selector: msg("{0} selector"),
};
