// The DynamicQuery enums (Signum's Signum.DynamicQuery.cs — a C#-autogenerated file in Signum, so
// NOT ported verbatim; these live here as real altea enums in the entities layer). They are the
// query-layer vocabulary shared by the client (Finder / SearchControl) and the server (query
// controller): filter operations/types, ordering, pagination, system-time, etc.
//
// Representation: each vocabulary term is a PAIR —
//   * `XEnum` — a NUMERIC enum (Signum's C# int-backed enum). Reserved for stored entity columns
//     (e.g. a future UserQueryEntity persists the mode as its ordinal). Not used at runtime/wire yet.
//   * `X = keyof typeof XEnum` — the STRING-LITERAL UNION of the member names ("IsIn" | …). This is
//     the client/runtime + wire form: FindOptions / Finder / QueryToken compare against bare string
//     literals exactly like Signum's React client, and the value that crosses altea/json IS the
//     member name string. Use the string literal ("IsIn") in query/client code; reach for `XEnum`
//     only when you need the numeric ordinal for entity storage.

import { msg } from './utils/localization';
import { registerEnum, setDatabaseSchema } from './registration';

// Query-token display messages (Signum's Signum.DynamicQuery.Tokens QueryTokenMessage /
// QueryTokenDateMessage, and Signum.External CollectionMessage — all C#-autogenerated resx there,
// here real altea LocalizableMessage containers). Used by QueryToken.getNiceTypeName / completeToken
// to name synthetic tokens; the display text arrives via the reflection translation blob (msg()'s
// name-inferred default is the fallback).
export const QueryTokenMessage = {
    _0Of1: msg("{0} of {1}"),
    AnyEntity: msg(),
    CellOperation: msg(),
    Check: msg(),
    ContainerOfCellOperations: msg(),
    Date: msg(),
    DateTime: msg(),
    DateTimeOffset: msg(),
    DecimalNumber: msg(),
    // The three qualifier words an aggregate's label is assembled from — Signum's
    // AggregateToken.GeNiceDistinct / GetNiceOperation / GetNiceValue read exactly these members.
    Distinct: msg(),
    EntityType: msg("Entity Type"),
    GlobalUniqueIdentifier: msg(),
    IndexerContainer: msg(),
    // The string `Length` sub-token's caption — an English literal until now, with nowhere for the
    // sync to hang Signum's German/Spanish.
    Length: msg(),
    ListOf0: msg("List of {0}"),
    Embedded0: msg("Embedded {0}"),
    // The numeric BUCKET tokens (Signum's DecimalSpecialTokens.cs). `Step0` / `_0Steps1` caption the
    // Step → xMultiplier → Rounding chain, `Modulo0` / `_0Mod1` the ModuloToken; `{0}` is the bucket
    // size, which is why each pair has a short (column-header) and a long (token-picker) form.
    Step0: msg("Step {0}"),
    _0Steps1: msg("{0} step {1}"),
    Modulo0: msg("Modulo {0}"),
    _0Mod1: msg("{0} mod {1}"),
    // Full-text search ranking (Signum's FullTextRankToken / PgTsRankToken / StringSnippetToken).
    MatchRank: msg("Match Rank"),
    MatchRankFor0: msg("Match Rank for {0}"),
    MatchSnippet: msg("Match Snippet"),
    SnippetOf0: msg("Snippet for {0}"),
    // Vector (embedding) search — the `Distance` sub-token of a @vectorIndex'd vector column, and the
    // name of the value type itself. Signum spells both of the first two as English string literals in
    // `VectorDistanceToken` ("Distance", "Distance for " + parent) and `VectorColumnToken.NiceTypeName`,
    // which is the same C1 defect the Step / Modulo / Length captions had: no member for a translation
    // to hang on.
    VectorDistance: msg("Distance"),
    VectorDistanceFor0: msg("Distance for {0}"),
    Vector: msg("Vector"),
    Not: msg(),
    Null: msg(),
    Number: msg(),
    Text: msg(),
};

// The caption of EVERY date/time sub-token, and the ONLY place one is spelled. A token that built its own
// label from its member name (`capitalize("dayOfWeek")`) showed that literal in every culture and, worse,
// had no member here for the sync to carry a translation on — which is how Signum's German and Spanish for
// these were deleted from Altea.<culture>.xml.
export const QueryTokenDateMessage = {
    Date: msg(),
    TimeOfDay: msg(),
    // The date/time PART tokens (QueryToken.dateTimeProperties / dateOnlyProperties).
    Year: msg(),
    Quarter: msg(),
    Month: msg(),
    WeekNumber: msg(),
    DayOfYear: msg(),
    Day: msg(),
    DayOfWeek: msg(),
    Hour: msg(),
    Minute: msg(),
    Second: msg(),
    Millisecond: msg(),
    // The Duration (Signum TimeSpan) tokens: `Days` is the whole-day COMPONENT, the `Total…` ones the
    // fractional whole-duration measure — `PT36H` is 1 day and 1.5 total days.
    Days: msg(),
    TotalDays: msg(),
    TotalHours: msg(),
    TotalMinutes: msg(),
    TotalSeconds: msg(),
    TotalMilliseconds: msg(),
    // The DatePartStartToken names, with Signum's own [Description] texts. The `Every0…` four are its
    // STEPPED variants and take the step as {0}.
    QuarterStart: msg("Quarter Start"),
    MonthStart: msg("Month Start"),
    WeekStart: msg("Week Start"),
    HourStart: msg("Hour Start"),
    MinuteStart: msg("Minute Start"),
    SecondStart: msg("Second Start"),
    Every0Hours: msg("Every {0} Hours"),
    Every0Minutes: msg("Every {0} Minutes"),
    Every0Seconds: msg("Every {0} Seconds"),
    Every0Milliseconds: msg("Every {0} Milliseconds"),
    Every01: msg("Every {0} {1}"),
    SplitQueries: msg("Split queries"),
    _0Steps1Rows2TotalRowsAprox: msg("{0} steps × {1} rows = {2} total rows (aprox)"),
};

// `Or` / `And` are the last separator of a comma-separated list — Signum's `CommaOr` / `CommaAnd`, which
// here is `array.joinComma(CollectionMessage.Or.niceToString())`. The SPACES are part of the value, exactly
// as in Signum's `[Description(" or ")]`: joinComma appends the separator with none of its own.
//
// `No0Found` / `MoreThanOne0Found` are what the exactly-one-element accessors throw — Signum raises them
// from `SingleEx` / `SingleOrDefaultEx`, altea from `Array.prototype.single` / `singleOrNull`
// (data/globals/arrayExtensions). {0} is the name of the thing being looked for.
export const CollectionMessage = {
    Or: msg(" or "),
    And: msg(" and "),
    No0Found: msg("No {0} found"),
    MoreThanOne0Found: msg("More than one {0} found"),
};

export enum ColumnOptionsMode {
    Add,
    Remove,
    ReplaceAll,
    InsertStart,
    ReplaceOrAdd,
}
export type ColumnOptionsModeKeys = keyof typeof ColumnOptionsMode;

export enum CombineRows {
    EqualValue,
    EqualEntity,
}
export type CombineRowsKeys = keyof typeof CombineRows;

export enum DashboardBehaviour {
    // Signum numbers this from 1: its slot 0 is a commented-out `ShowAsPartFilter` it kept the value of
    // rather than reusing. The values ARE the stored ids of the enum table, so starting at 0 renumbers
    // every row — which a sync then has to perform as a three-pass shuffle through scratch ids (each
    // member out of the way, the diff, then back), because two members cannot hold one id even for a
    // statement. Forty statements of churn from one wrong base value.
    PromoteToDasboardPinnedFilter = 1,
    UseAsInitialSelection,
    UseWhenNoFilters,
}
export type DashboardBehaviourKeys = keyof typeof DashboardBehaviour;

export enum FilterGroupOperation {
    And,
    Or,
}
export type FilterGroupOperationKeys = keyof typeof FilterGroupOperation;

export enum FilterOperation {
    EqualTo,
    DistinctTo,
    GreaterThan,
    GreaterThanOrEqual,
    LessThan,
    LessThanOrEqual,
    Contains,
    StartsWith,
    EndsWith,
    Like,
    NotContains,
    NotStartsWith,
    NotEndsWith,
    NotLike,
    IsIn,
    IsNotIn,
    ComplexCondition,
    FreeText,
    TsQuery,
    TsQuery_Plain,
    TsQuery_Phrase,
    TsQuery_WebSearch,
    SmartSearch,
    Between,
    BetweenNoEnd,
}
export type FilterOperationKeys = keyof typeof FilterOperation;

export enum FilterType {
    Integer,
    Decimal,
    String,
    DateTime,
    Time,
    Lite,
    Embedded,
    Model,
    Boolean,
    Enum,
    Guid,
    TsVector,
    Vector,
}
export type FilterTypeKeys = keyof typeof FilterType;

export enum OrderType {
    Ascending,
    Descending,
}
export type OrderTypeKeys = keyof typeof OrderType;

export enum PaginationMode {
    All,
    Firsts,
    Paginate,
}
export type PaginationModeKeys = keyof typeof PaginationMode;

export enum PinnedFilterActive {
    Always,
    WhenHasValue,
    Checkbox_Checked,
    Checkbox_Unchecked,
    NotCheckbox_Checked,
    NotCheckbox_Unchecked,
}
export type PinnedFilterActiveKeys = keyof typeof PinnedFilterActive;

// The per-enum `values()`/`niceToString()` companions that used to live here are gone — the ported
// query UI now uses the single entity-level `Enum` helper (entities/enum) over the numeric `XEnum`
// objects: `Enum.values(FilterGroupOperationEnum)` / `Enum.niceName(FilterOperationEnum, x)`.

export enum RefreshMode {
    Auto,
    Manual,
}
export type RefreshModeKeys = keyof typeof RefreshMode;

export enum SystemTimeJoinMode {
    Current,
    FirstCompatible,
    AllCompatible,
}
export type SystemTimeJoinModeKeys = keyof typeof SystemTimeJoinMode;

export enum SystemTimeMode {
    AsOf,
    Between,
    ContainedIn,
    All,
    TimeSeries,
}
export type SystemTimeModeKeys = keyof typeof SystemTimeMode;

export enum TimeSeriesUnit {
    Year,
    Quarter,
    Month,
    Week,
    Day,
    Hour,
    Minute,
    Second,
    Millisecond,
}
export type TimeSeriesUnitKeys = keyof typeof TimeSeriesUnit;

export enum UniqueType {
    First,
    FirstOrDefault,
    Single,
    SingleOrDefault,
    Only,
}
export type UniqueTypeKeys = keyof typeof UniqueType;

// Register the DynamicQuery-vocabulary enums that are PERSISTED as entity fields (Signum ships these as
// real int-backed enums with their own table, e.g. UserQueryEntity.columnsMode / UserQueryEntity_Order.orderType).
// Registering an enum here only makes it resolvable as an enum type; a table is created lazily by the
// schema builder only when a FieldEnum actually references it (so registering the unused ones is harmless).
//
// altea divergence: the query layer uses the string-union TYPE alias (`OrderType`) at runtime, so the enum
// OBJECT must keep the `Enum` suffix (`OrderTypeEnum`) — the registered clean name / table name therefore
// carries that suffix (Signum's "OrderType" → altea "OrderTypeEnum"). The runtime/wire value stays the member
// NAME string (EnumSerializer), so query/FindOptions code is unaffected; only the DB column becomes an int FK
// to the enum table (translatable), and the in-memory field value is the numeric ordinal (like OrderState) —
// callers that need the string name normalise with `Enum.toName`. The registerEnum() calls below are rewritten
// by the quote-transformer to `registerEnum(X, "X", __fileInfo)`.
registerEnum(ColumnOptionsMode);
registerEnum(CombineRows);
registerEnum(DashboardBehaviour);
registerEnum(FilterGroupOperation);
registerEnum(FilterOperation);
registerEnum(OrderType);
registerEnum(PaginationMode);
registerEnum(PinnedFilterActive);
registerEnum(RefreshMode);
registerEnum(SystemTimeJoinMode);
registerEnum(SystemTimeMode);
registerEnum(TimeSeriesUnit);

// These twelve are Signum's `Signum.DynamicQuery` namespace, which the core assembly maps to the
// `queries` SCHEMA (`[assembly: AssemblySchemaName("queries", ForNamespace = "Signum.DynamicQuery")]`).
// altea groups its core model by role rather than by target schema, so they sit in this file beside the
// `basics` types that @altea/altea/data declares — hence the per-type override, one per line so adding
// or moving one is a single-line diff. See setDatabaseSchema.
setDatabaseSchema("queries",
    ColumnOptionsMode,
    CombineRows,
    DashboardBehaviour,
    FilterGroupOperation,
    FilterOperation,
    OrderType,
    PaginationMode,
    PinnedFilterActive,
    RefreshMode,
    SystemTimeJoinMode,
    SystemTimeMode,
    TimeSeriesUnit,
);
