// The DynamicQuery enums (Signum's Signum.DynamicQuery.cs — a C#-autogenerated file in Signum, so
// NOT ported verbatim; these live here as real altea enums in the entities layer). They are the
// query-layer vocabulary shared by the client (Finder / SearchControl) and the server (query
// controller): filter operations/types, ordering, pagination, system-time, etc.
//
// Representation: each vocabulary term is a PAIR —
//   * `XEnum` — a NUMERIC enum (Signum's C# int-backed enum). Reserved for stored entity columns
//     (e.g. a future UserQueryEntity persists the mode as its ordinal). Not used at runtime/wire yet.
//   * `X = keyof typeof XEnum` — the STRING-LITERAL UNION of the member names ("IsIn" | …). This is
//     the client/runtime + wire form: FindOptions / Finder / QueryToken compare against bare string
//     literals exactly like Signum's React client, and the value that crosses altea/json IS the
//     member name string. Use the string literal ("IsIn") in query/client code; reach for `XEnum`
//     only when you need the numeric ordinal for entity storage.

import { msg } from './utils/localization';
import { registerEnum } from './registration';

// Query-token display messages (Signum's Signum.DynamicQuery.Tokens QueryTokenMessage /
// QueryTokenDateMessage, and Signum.External CollectionMessage — all C#-autogenerated resx there,
// here real altea LocalizableMessage containers). Used by QueryToken.getNiceTypeName / completeToken
// to name synthetic tokens; the display text arrives via the reflection translation blob (msg()'s
// name-inferred default is the fallback).
export const QueryTokenMessage = {
    AnyEntity: msg(),
    CellOperation: msg(),
    Check: msg(),
    ContainerOfCellOperations: msg(),
    Date: msg(),
    DateTime: msg(),
    DateTimeOffset: msg(),
    DecimalNumber: msg(),
    GlobalUniqueIdentifier: msg(),
    IndexerContainer: msg(),
    ListOf0: msg("List of {0}"),
    Embedded0: msg("Embedded {0}"),
    Number: msg(),
    Text: msg(),
};

export const QueryTokenDateMessage = {
    Date: msg(),
    TimeOfDay: msg(),
    Every01: msg("Every {0} {1}"),
    SplitQueries: msg("Split queries"),
    _0Steps1Rows2TotalRowsAprox: msg("{0} steps × {1} rows = {2} total rows (aprox)"),
};

export const CollectionMessage = {
    Or: msg(),
    And: msg(),
};

export enum ColumnOptionsModeEnum {
    Add,
    Remove,
    ReplaceAll,
    InsertStart,
    ReplaceOrAdd,
}
export type ColumnOptionsMode = keyof typeof ColumnOptionsModeEnum;

export enum CombineRowsEnum {
    EqualValue,
    EqualEntity,
}
export type CombineRows = keyof typeof CombineRowsEnum;

export enum DashboardBehaviourEnum {
    PromoteToDasboardPinnedFilter,
    UseAsInitialSelection,
    UseWhenNoFilters,
}
export type DashboardBehaviour = keyof typeof DashboardBehaviourEnum;

export enum FilterGroupOperationEnum {
    And,
    Or,
}
export type FilterGroupOperation = keyof typeof FilterGroupOperationEnum;

export enum FilterOperationEnum {
    EqualTo,
    DistinctTo,
    GreaterThan,
    GreaterThanOrEqual,
    LessThan,
    LessThanOrEqual,
    Contains,
    StartsWith,
    EndsWith,
    Like,
    NotContains,
    NotStartsWith,
    NotEndsWith,
    NotLike,
    IsIn,
    IsNotIn,
    ComplexCondition,
    FreeText,
    TsQuery,
    TsQuery_Plain,
    TsQuery_Phrase,
    TsQuery_WebSearch,
    SmartSearch,
    Between,
    BetweenNoEnd,
}
export type FilterOperation = keyof typeof FilterOperationEnum;

export enum FilterTypeEnum {
    Integer,
    Decimal,
    String,
    DateTime,
    Time,
    Lite,
    Embedded,
    Model,
    Boolean,
    Enum,
    Guid,
    TsVector,
    Vector,
}
export type FilterType = keyof typeof FilterTypeEnum;

export enum OrderTypeEnum {
    Ascending,
    Descending,
}
export type OrderType = keyof typeof OrderTypeEnum;

export enum PaginationModeEnum {
    All,
    Firsts,
    Paginate,
}
export type PaginationMode = keyof typeof PaginationModeEnum;

export enum PinnedFilterActiveEnum {
    Always,
    WhenHasValue,
    Checkbox_Checked,
    Checkbox_Unchecked,
    NotCheckbox_Checked,
    NotCheckbox_Unchecked,
}
export type PinnedFilterActive = keyof typeof PinnedFilterActiveEnum;

// The per-enum `values()`/`niceToString()` companions that used to live here are gone — the ported
// query UI now uses the single entity-level `Enum` helper (entities/enum) over the numeric `XEnum`
// objects: `Enum.values(FilterGroupOperationEnum)` / `Enum.niceName(FilterOperationEnum, x)`.

export enum RefreshModeEnum {
    Auto,
    Manual,
}
export type RefreshMode = keyof typeof RefreshModeEnum;

export enum SystemTimeJoinModeEnum {
    Current,
    FirstCompatible,
    AllCompatible,
}
export type SystemTimeJoinMode = keyof typeof SystemTimeJoinModeEnum;

export enum SystemTimeModeEnum {
    AsOf,
    Between,
    ContainedIn,
    All,
    TimeSeries,
}
export type SystemTimeMode = keyof typeof SystemTimeModeEnum;

export enum TimeSeriesUnitEnum {
    Year,
    Quarter,
    Month,
    Week,
    Day,
    Hour,
    Minute,
    Second,
    Millisecond,
}
export type TimeSeriesUnit = keyof typeof TimeSeriesUnitEnum;

export enum UniqueTypeEnum {
    First,
    FirstOrDefault,
    Single,
    SingleOrDefault,
    Only,
}
export type UniqueType = keyof typeof UniqueTypeEnum;

// Register the DynamicQuery-vocabulary enums that are PERSISTED as entity fields (Signum ships these as
// real int-backed enums with their own table, e.g. UserQueryEntity.ColumnsMode / QueryOrderEmbedded.OrderType).
// Registering an enum here only makes it resolvable as an enum type; a table is created lazily by the
// schema builder only when a FieldEnum actually references it (so registering the unused ones is harmless).
//
// altea divergence: the query layer uses the string-union TYPE alias (`OrderType`) at runtime, so the enum
// OBJECT must keep the `Enum` suffix (`OrderTypeEnum`) — the registered clean name / table name therefore
// carries that suffix (Signum's "OrderType" → altea "OrderTypeEnum"). The runtime/wire value stays the member
// NAME string (EnumSerializer), so query/FindOptions code is unaffected; only the DB column becomes an int FK
// to the enum table (translatable), and the in-memory field value is the numeric ordinal (like OrderState) —
// callers that need the string name normalise with `Enum.toName`. The registerEnum() calls below are rewritten
// by the quote-transformer to `registerEnum(X, "X", __fileInfo)`.
registerEnum(ColumnOptionsModeEnum);
registerEnum(CombineRowsEnum);
registerEnum(DashboardBehaviourEnum);
registerEnum(FilterGroupOperationEnum);
registerEnum(FilterOperationEnum);
registerEnum(OrderTypeEnum);
registerEnum(PaginationModeEnum);
registerEnum(PinnedFilterActiveEnum);
registerEnum(RefreshModeEnum);
registerEnum(SystemTimeJoinModeEnum);
registerEnum(SystemTimeModeEnum);
registerEnum(TimeSeriesUnitEnum);
