// The DynamicQuery enums (Signum's Signum.DynamicQuery.cs — a C#-autogenerated file in Signum, so
// NOT ported verbatim; these live here as real altea enums in the entities layer). They are the
// query-layer vocabulary shared by the client (Finder / SearchControl) and the server (query
// controller): filter operations/types, ordering, pagination, system-time, etc.
//
// Representation: each vocabulary term is a PAIR —
//   * `XEnum` — a NUMERIC enum (Signum's C# int-backed enum). Reserved for stored entity columns
//     (e.g. a future UserQueryEntity persists the mode as its ordinal). Not used at runtime/wire yet.
//   * `X = keyof typeof XEnum` — the STRING-LITERAL UNION of the member names ("IsIn" | …). This is
//     the client/runtime + wire form: FindOptions / Finder / QueryToken compare against bare string
//     literals exactly like Signum's React client, and the value that crosses altea/json IS the
//     member name string. Use the string literal ("IsIn") in query/client code; reach for `XEnum`
//     only when you need the numeric ordinal for entity storage.

import { msg } from './utils/localization';
import { registerEnum, setDatabaseSchema } from './registration';

// Query-token display messages (Signum's Signum.DynamicQuery.Tokens QueryTokenMessage /
// QueryTokenDateMessage, and Signum.External CollectionMessage — all C#-autogenerated resx there,
// here real altea LocalizableMessage containers). Used by QueryToken.getNiceTypeName / completeToken
// to name synthetic tokens; the display text arrives via the reflection translation blob (msg()'s
// name-inferred default is the fallback).
export const QueryTokenMessage = {
    _0Of1: msg("{0} of {1}"),
    AnyEntity: msg(),
    CellOperation: msg(),
    Check: msg(),
    ContainerOfCellOperations: msg(),
    Date: msg(),
    DateTime: msg(),
    DateTimeOffset: msg(),
    DecimalNumber: msg(),
    // The three qualifier words an aggregate's label is assembled from — Signum's
    // AggregateToken.GeNiceDistinct / GetNiceOperation / GetNiceValue read exactly these members.
    Distinct: msg(),
    EntityType: msg("Entity Type"),
    GlobalUniqueIdentifier: msg(),
    IndexerContainer: msg(),
    ListOf0: msg("List of {0}"),
    Embedded0: msg("Embedded {0}"),
    Not: msg(),
    Null: msg(),
    Number: msg(),
    Text: msg(),
};

export const QueryTokenDateMessage = {
    Date: msg(),
    TimeOfDay: msg(),
    // The DatePartStartToken names, with Signum's own [Description] texts.
    QuarterStart: msg("Quarter Start"),
    MonthStart: msg("Month Start"),
    WeekStart: msg("Week Start"),
    HourStart: msg("Hour Start"),
    MinuteStart: msg("Minute Start"),
    SecondStart: msg("Second Start"),
    Every01: msg("Every {0} {1}"),
    SplitQueries: msg("Split queries"),
    _0Steps1Rows2TotalRowsAprox: msg("{0} steps × {1} rows = {2} total rows (aprox)"),
};

// The last separator of a comma-separated list — Signum's `CommaOr` / `CommaAnd`, which here is
// `array.joinComma(CollectionMessage.Or.niceToString())`. The SPACES are part of the value, exactly as in
// Signum's `[Description(" or ")]`: joinComma appends the separator with none of its own.
export const CollectionMessage = {
    Or: msg(" or "),
    And: msg(" and "),
};

export enum ColumnOptionsMode {
    Add,
    Remove,
    ReplaceAll,
    InsertStart,
    ReplaceOrAdd,
}
export type ColumnOptionsModeKeys = keyof typeof ColumnOptionsMode;

export enum CombineRows {
    EqualValue,
    EqualEntity,
}
export type CombineRowsKeys = keyof typeof CombineRows;

export enum DashboardBehaviour {
    // Signum numbers this from 1: its slot 0 is a commented-out `ShowAsPartFilter` it kept the value of
    // rather than reusing. The values ARE the stored ids of the enum table, so starting at 0 renumbers
    // every row — which a sync then has to perform as a three-pass shuffle through scratch ids (each
    // member out of the way, the diff, then back), because two members cannot hold one id even for a
    // statement. Forty statements of churn from one wrong base value.
    PromoteToDasboardPinnedFilter = 1,
    UseAsInitialSelection,
    UseWhenNoFilters,
}
export type DashboardBehaviourKeys = keyof typeof DashboardBehaviour;

export enum FilterGroupOperation {
    And,
    Or,
}
export type FilterGroupOperationKeys = keyof typeof FilterGroupOperation;

export enum FilterOperation {
    EqualTo,
    DistinctTo,
    GreaterThan,
    GreaterThanOrEqual,
    LessThan,
    LessThanOrEqual,
    Contains,
    StartsWith,
    EndsWith,
    Like,
    NotContains,
    NotStartsWith,
    NotEndsWith,
    NotLike,
    IsIn,
    IsNotIn,
    ComplexCondition,
    FreeText,
    TsQuery,
    TsQuery_Plain,
    TsQuery_Phrase,
    TsQuery_WebSearch,
    SmartSearch,
    Between,
    BetweenNoEnd,
}
export type FilterOperationKeys = keyof typeof FilterOperation;

export enum FilterType {
    Integer,
    Decimal,
    String,
    DateTime,
    Time,
    Lite,
    Embedded,
    Model,
    Boolean,
    Enum,
    Guid,
    TsVector,
    Vector,
}
export type FilterTypeKeys = keyof typeof FilterType;

export enum OrderType {
    Ascending,
    Descending,
}
export type OrderTypeKeys = keyof typeof OrderType;

export enum PaginationMode {
    All,
    Firsts,
    Paginate,
}
export type PaginationModeKeys = keyof typeof PaginationMode;

export enum PinnedFilterActive {
    Always,
    WhenHasValue,
    Checkbox_Checked,
    Checkbox_Unchecked,
    NotCheckbox_Checked,
    NotCheckbox_Unchecked,
}
export type PinnedFilterActiveKeys = keyof typeof PinnedFilterActive;

// The per-enum `values()`/`niceToString()` companions that used to live here are gone — the ported
// query UI now uses the single entity-level `Enum` helper (entities/enum) over the numeric `XEnum`
// objects: `Enum.values(FilterGroupOperationEnum)` / `Enum.niceName(FilterOperationEnum, x)`.

export enum RefreshMode {
    Auto,
    Manual,
}
export type RefreshModeKeys = keyof typeof RefreshMode;

export enum SystemTimeJoinMode {
    Current,
    FirstCompatible,
    AllCompatible,
}
export type SystemTimeJoinModeKeys = keyof typeof SystemTimeJoinMode;

export enum SystemTimeMode {
    AsOf,
    Between,
    ContainedIn,
    All,
    TimeSeries,
}
export type SystemTimeModeKeys = keyof typeof SystemTimeMode;

export enum TimeSeriesUnit {
    Year,
    Quarter,
    Month,
    Week,
    Day,
    Hour,
    Minute,
    Second,
    Millisecond,
}
export type TimeSeriesUnitKeys = keyof typeof TimeSeriesUnit;

export enum UniqueType {
    First,
    FirstOrDefault,
    Single,
    SingleOrDefault,
    Only,
}
export type UniqueTypeKeys = keyof typeof UniqueType;

// Register the DynamicQuery-vocabulary enums that are PERSISTED as entity fields (Signum ships these as
// real int-backed enums with their own table, e.g. UserQueryEntity.columnsMode / UserQueryEntity_Order.orderType).
// Registering an enum here only makes it resolvable as an enum type; a table is created lazily by the
// schema builder only when a FieldEnum actually references it (so registering the unused ones is harmless).
//
// altea divergence: the query layer uses the string-union TYPE alias (`OrderType`) at runtime, so the enum
// OBJECT must keep the `Enum` suffix (`OrderTypeEnum`) — the registered clean name / table name therefore
// carries that suffix (Signum's "OrderType" → altea "OrderTypeEnum"). The runtime/wire value stays the member
// NAME string (EnumSerializer), so query/FindOptions code is unaffected; only the DB column becomes an int FK
// to the enum table (translatable), and the in-memory field value is the numeric ordinal (like OrderState) —
// callers that need the string name normalise with `Enum.toName`. The registerEnum() calls below are rewritten
// by the quote-transformer to `registerEnum(X, "X", __fileInfo)`.
registerEnum(ColumnOptionsMode);
registerEnum(CombineRows);
registerEnum(DashboardBehaviour);
registerEnum(FilterGroupOperation);
registerEnum(FilterOperation);
registerEnum(OrderType);
registerEnum(PaginationMode);
registerEnum(PinnedFilterActive);
registerEnum(RefreshMode);
registerEnum(SystemTimeJoinMode);
registerEnum(SystemTimeMode);
registerEnum(TimeSeriesUnit);

// These twelve are Signum's `Signum.DynamicQuery` namespace, which the core assembly maps to the
// `queries` SCHEMA (`[assembly: AssemblySchemaName("queries", ForNamespace = "Signum.DynamicQuery")]`).
// altea groups its core model by role rather than by target schema, so they sit in this file beside the
// `basics` types that @altea/altea/data declares — hence the per-type override, one per line so adding
// or moving one is a single-line diff. See setDatabaseSchema.
setDatabaseSchema("queries",
    ColumnOptionsMode,
    CombineRows,
    DashboardBehaviour,
    FilterGroupOperation,
    FilterOperation,
    OrderType,
    PaginationMode,
    PinnedFilterActive,
    RefreshMode,
    SystemTimeJoinMode,
    SystemTimeMode,
    TimeSeriesUnit,
);
