// Client UI message containers (Signum's Signum.Entities EntityControlMessage / SelectorMessage /
// JavascriptMessage / SearchMessage — C#-autogenerated there, real altea LocalizableMessage
// containers here). Only the members the ported Lines / SelectorModal / Constructor use so far; add
// more as further components land. Display text arrives via the reflection translation blob; the
// msg() name-inferred / explicit default is the fallback.
import { msg } from './utils/localization';
import { Enum } from './enum';
import { registerEnum } from './registration';

export const EntityControlMessage = {
    Add: msg("Add"),
    Create: msg(),
    Find: msg(),
    Paste: msg(),
    Remove: msg(),
    View: msg(),
    MoveUp: msg("Move up"),
    MoveDown: msg("Move down"),
    MoveRight: msg("Move right"),
    MoveLeft: msg("Move left"),
    MoveWithDragAndDropOrCtrlUpDown: msg("Move (with drag and drop or Ctrl + Up / Down)"),
    MoveWithDragAndDropOrCtrlLeftRight: msg("Move (with drag and drop or Ctrl + Left / Right)"),
    Close: msg("Close"),
    Reload: msg("Reload"),
    Changed: msg("Changed"),
    NoChanges: msg("No changes"),
    // The version-diff vocabulary the Time Machine's "UI differences" tab renders through
    // `getTimeMachineIcon` (Lines/TimeMachineIcon). They live here, beside the rest of the Lines
    // messages, because the ICON is a core Line concern — @altea/altea-time-machine only supplies the
    // `previousVersion` on the TypeContext that switches it on.
    PreviousValueWas0: msg("Previous value was: {0}"),
    Moved: msg("Moved"),
    Removed0: msg("Removed {0}"),
    Added: msg("Added"),
    RemovedAndSelectedAgain: msg("Removed and selected again"),
    Selected: msg("Selected"),
    // Signum's EntityControlMessage.ToggleSideBar — used by the sidebar toggle in the navbar
    // (@altea/altea-toolbar's SidebarToggleItem), which is why it lives with the framework messages.
    ToggleSideBar: msg("Toggle side bar"),
};

export const JavascriptMessage = {
    ok: msg("OK"),
    cancel: msg("Cancel"),
    yes: msg("Yes"),
    no: msg("No"),
    executed: msg("Executed"),
    error: msg("Error"),
    Close: msg("Close"),
    loading: msg("Loading…"),
    Date: msg("Date"),
    Selected: msg("Selected"),
    addFilter: msg("Add filter"),
    editColumn: msg("Edit column"),
    groupByThisColumn: msg("Group by this column"),
    insertColumn: msg("Insert column"),
    noActionsFound: msg("No actions found"),
    removeColumn: msg("Remove column"),
    removeOtherColumns: msg("Remove other columns"),
    restoreDefaultColumns: msg("Restore default columns"),
    searchForResults: msg("Search for results"),
    ShowGroup: msg("Show group"),
    loseCurrentChanges: msg("There are changes in the current entity without saving. Do you want to lose them?"),
    saveChangesBeforeOrPressCancel: msg("Save changes before or press cancel"),
};

export const FrameMessage = {
    Fullscreen: msg("Fullscreen"),
    ThereAreErrors: msg("There are errors"),
    Main: msg("Main"),
    Copied: msg("Copied"),
};

// SaveChanges (Signum's SaveChangesMessage) — the lose-changes modal.
export const SaveChangesMessage = {
    ThereAreChanges: msg("There are changes"),
    YoureTryingToCloseAnEntityWithChanges: msg("You're trying to close an entity with changes. What do you want to do?"),
    LoseChanges: msg("Lose changes"),
};

export const SearchMessage = {
    Operations: msg("Operations"),
    Search: msg("Search"),
    View: msg("View"),
    CreateNew0_G: msg("Create new {0}"),
    AddValue: msg("Add value"),
    DeleteFilter: msg("Delete filter"),
    DeleteAllFilter: msg("Delete all filters"),
    Field: msg("Field"),
    Operator: msg("Operator"),
    Value: msg("Value"),
    Label: msg("Label"),
    Column: msg("Column"),
    ColSpan: msg("Col span"),
    Row: msg("Row"),
    IsActive: msg("Is active"),
    Split: msg("Split"),
    AddFilter: msg("Add filter"),
    AddOrGroup: msg("Add OR group"),
    AddAndGroup: msg("Add AND group"),
    EditPinnedFilters: msg("Edit pinned filters"),
    OrGroup: msg("Or Group"),
    AndGroup: msg("And Group"),
    PinFilter: msg("Pin filter"),
    UnpinFilter: msg("Unpin filter"),
    ParentValue: msg("Parent value"),
    Enter: msg("Enter"),
    SplitsTheValuesAndSearchesEachOneIndependentlyInAnANDGroup: msg("Splits the values and searches each one independently in an AND group"),
    SplitsTheStringValueBySpaceAndSearchesEachPartIndependentlyInAnANDGroup: msg("Splits the string value by space and searches each part independently in an AND group"),
    // Pagination
    _0Results_N: msg("{0} results"),
    First0Results_N: msg("First {0} results"),
    NoResultsInThisPage: msg("No results in this page"),
    _01of2Results_N: msg("{0} - {1} of {2} results"),
    PaginationAll_0Elements: msg("Show {0} elements"),
    PaginationFirst_01Elements: msg("Show first {0} of {1} elements"),
    PaginationPages_0Of01lements: msg("{0} of {1} elements"),
    PaginationMode: msg("Pagination mode"),
    NumberOfElementsForPagination: msg("Number of elements per page"),
    // Column editor
    ColumnField: msg("Field"),
    ShowMore: msg("Show more"),
    SummaryHeader: msg("Summary header"),
    DisplayName: msg("Display name"),
    CombineRowsWith: msg("Combine rows with"),
    Equal0: msg("Equal {0}"),
    InvalidColumnExpression: msg("Invalid column expression"),
    CollectionsCanNotBeAddedAsColumns: msg("Collections can not be added as columns"),
    SummaryHeaderMustBeAnAggregate: msg("Summary header must be an aggregate"),
    // SearchControlLoaded toolbar / results / context menu
    AdvancedFilters: msg("Advanced filters"),
    After: msg("After"),
    AllPages: msg("All pages"),
    Before: msg("Before"),
    Columns: msg("Columns"),
    Copy: msg("Copy"),
    CurrentPage: msg("Current page"),
    DerivedGroupKey: msg("Derived group key"),
    EditAllColumns: msg("Edit all columns"),
    FilterDesigner: msg("Filter designer"),
    FilterMenu: msg("Filter menu"),
    FilterTypeSelection: msg("Select filter type"),
    Filters: msg("Filters"),
    GoBackToPageOne: msg("Go back to page one"),
    GroupKey: msg("Group key"),
    HideHiddenColumns: msg("Hide hidden columns"),
    MoreThanOne0Selected: msg("More than one {0} selected"),
    NoResultsFound: msg("No results found"),
    NoResultsFoundInPage01: msg("No results found in page {0} of {1}"),
    OperationsForSelectedElements: msg("Operations for selected elements"),
    Refresh: msg("Refresh"),
    SelectAllResults: msg("Select all results"),
    ShowHiddenColumns: msg("Show hidden columns"),
    SimpleFilters: msg("Simple filters"),
    SwitchViewMode: msg("Switch view mode"),
    TimeMachine: msg("Time machine"),
    ToPreventPerformanceIssuesAutomaticSearchIsDisabledCheckYourFiltersAndThenClickSearchButton: msg("To prevent performance issues automatic search is disabled. Check your filters and then click the search button"),
    YouHaveSelectedAllRowsOnThisPageDoYouWantTo0OnlyTheseRowsOrToAllRowsAcrossAllPages: msg("You have selected all rows on this page. Do you want to {0} only these rows or all rows across all pages?"),
    _0GroupWith1_N: msg("{0} group with {1}"),
    _0ResultTable: msg("{0} result table"),
    // SearchModal
    ReturnNewEntity: msg("Return new entity"),
    DoYouWantToSelectTheNew01_G: msg("Do you want to select the new {0} {1}?"),
    PleaseSelectOneOrMore0_G: msg("Please select one or more {0}"),
    PleaseSelectOneOrSeveralEntities: msg("Please select one or several entities"),
    PleaseSelectA0_G: msg("Please select a {0}"),
    PleaseSelectAnEntity: msg("Please select an entity"),
};

export const SelectorMessage = {
    ChooseAValue: msg("Choose a value"),
    ChooseValues: msg("Choose values"),
    PleaseChooseA0ToContinue: msg("Please choose a {0} to continue"),
    PleaseChooseAValueToContinue: msg("Please choose a value to continue"),
    PleaseSelectAConstructor: msg("Please select a constructor"),
    PleaseSelectAType: msg("Please select a type"),
    PleaseSelectAtLeastOneValueToContinue: msg("Please select at least one value to continue"),
    TypeSelector: msg("Type selector"),
    _0Selector: msg("{0} selector"),
};

// Operations (Signum's OperationMessage). Members used by the Operations client layer.
export const OperationMessage = {
    Create: msg("Create…"),
    // Simplifies a ConstructorFrom nice name inside a Create group ("Create Order from Customer" → group 1).
    CreateFromRegex: msg("^Create (.+?)( from .+)?$"),
    Create0: msg("Create {0}"),
    Confirm: msg("Confirm"),
    PleaseConfirmYouWouldLikeToDelete0FromTheSystem: msg("Please confirm that you would like to delete {0} from the system"),
    As: msg("as"),
    PleaseConfirmYouWouldLikeTo01: msg("Please confirm you would like to {0} {1}"),
    _0AndClose: msg("{0} and close"),
    _0AndNew: msg("{0} and new"),
    MultiSetter: msg("(Multi setter)"),
    // Signum's OperationMessage.StateShouldBe0InsteadOf1 — why a state-machine operation cannot run over
    // the current selection (see OperationLogic.getContextualCanExecute).
    StateShouldBe0InsteadOf1: msg("State should be {0} instead of {1}"),
    // Why an operation was refused (OperationLogic.operationAllowedMessage). {0} is the operation's nice
    // name, {1} its key. `InUserInterface` is APPENDED when the refusal was the button-state check — the
    // same operation may still be allowed to server code, and saying so is what makes the two answers
    // distinguishable in a log.
    Operation01IsNotAuthorized: msg("Operation {0} ({1}) is not Authorized"),
    InUserInterface: msg("(in user interface)"),
    // The caption of the `Logs` token over OperationSymbol.logs() — every execution of THAT operation,
    // from the operation symbol's own search page. A message rather than a property name for the reason
    // `Duration` below gives.
    Logs: msg(),
    // The `PreviousOperationLog` extension token OperationLogic registers on every @systemVersioned
    // type — "which operation produced this row version" (see OperationLogic.registerPreviousLog).
    PreviousOperationLog: msg("Previous operation log"),
    // The two system-time tokens registered beside it (see OperationLogic.registerSystemValidTokens):
    // when a row version was current. Signum names them Entity.SystemValidFrom / .SystemValidTo.
    SystemValidFrom: msg("System valid from"),
    SystemValidTo: msg("System valid to"),
    // The caption of the `Duration` token over OperationLogEntity.durationMilliseconds(). Signum has it
    // as the PROPERTY OperationLogEntity.Duration, translated under that type's <Type> block; altea's
    // member is a `@quoted` method, which is not a PropertyRoute and therefore has no <Member> entry of
    // its own, so the localizable name has to be a message. Same reason as the two tokens above.
    Duration: msg(),
    Executing0: msg("Executing {0}"),
    Deleting: msg("Deleting…"),
    _0Errors: msg("{0} errors"),
    CancelOperation: msg("Cancel operation"),
    AreYouSureYouWantToCancelTheOperation: msg("Are you sure you want to cancel the operation?"),
    ClosingThisModalOrBrowserTabWillCancelTheOperation: msg("Closing this modal or browser tab will cancel the operation"),
    PleaseConfirmThatYouWouldLikeToApplyTheAboveChangesAndExecute0Over12: msg("Please confirm that you would like to apply the above changes and execute {0} over {1} {2}"),
    // The multi-setter dialog (Operations/MultiPropertySetter): its title, its third column header, and
    // the two headings of a nested setter block.
    BulkModifications: msg("Bulk modifications"),
    Operation: msg("Operation"),
    Condition: msg("Condition"),
    Setters: msg("Setters"),
    AddSetter: msg("Add setter"),
};

// Engine (Signum's EngineMessage) — the members the Operations layer reads.
export const EngineMessage = {
    TheEntity0IsNew: msg("The entity {0} is new"),
    // Signum's EngineMessage.EntityWithType0AndId1NotFound — shown when a stored/urled id no longer resolves
    // (e.g. @altea/altea-toolbar's entity-scoped menu restoring its last selection).
    _01NotFound: msg("{0} with Id {1} not found"),
    // The four sentences a constraint violation is re-raised as — see server/connection/
    // databaseExceptions (Signum's ForeignKeyException / UniqueKeyException). The first pair is a
    // DELETE blocked by rows that still point at the row being removed, with and without a known entity
    // type behind the table; the second is a unique index rejecting a duplicate, with and without the
    // offending values. `_G` = the article varies with the type's grammatical gender
    // (`forGenderAndNumber`), exactly as in Signum.
    ThereAre0ThatReferThisEntityByProperty1: msg("There are '{0}' that refer to this entity by property '{1}'"),
    ThereAreRecordsIn0PointingToThisTableByColumn1: msg("There are records in '{0}' referring to this table by column '{1}'"),
    ThereIsAlreadyA0With1EqualsTo2_G: msg("There is already a {0} with {1} equals to {2}"),
    ThereIsAlreadyA0WithTheSame1_G: msg("There is already a {0} with the same {1}"),
};

// NormalControl (Signum's NormalControlMessage) — the members the Operations layer reads.
export const NormalControlMessage = {
    SaveChangesFirst: msg("Save changes first!"),
    CopyEntityTypeAndIdForAutocomplete: msg("Copy entity type and id (for autocomplete)"),
    CopyEntityUrl: msg("Copy entity URL"),
};

// Connection (Signum's ConnectionMessage) — used by ErrorModal.
export const ConnectionMessage = {
    VersionInfo: msg("Version info"),
    ANewVersionHasJustBeenDeployedSaveChangesAnd0: msg("A new version has just been deployed! Save changes and {0}"),
    OutdatedClientApplication: msg("This application has been updated, please refresh the page!"),
    ANewVersionHasJustBeenDeployedConsiderReload: msg("A new version has just been deployed! Consider reloading the page."),
    Refresh: msg("Refresh"),
};

// QuickLink (Signum's QuickLinkMessage) — used by the QuickLinkClient widget / context menu / cell links.
export const QuickLinkMessage = {
    Quicklinks: msg("Quicklinks"),
    No0Found: msg("No {0} found"),
};

// CollapsableCard (Signum's CollapsableCardMessage, Signum.Basics) — the expand/collapse toggle title.
export const CollapsableCardMessage = {
    Collapse: msg("Collapse"),
    Expand: msg("Expand"),
};

// CascadeDelete (Signum's CascadeDeleteMessage) — used by DeleteErrorModal.
export const CascadeDeleteMessage = {
    ThisEntityIsStillReferenced: msg("This entity is still referenced"),
    TheFollowingEntitiesStillReference0RemoveThemBeforeDeleting: msg("The following entities still reference {0}. Remove them before deleting."),
    NoReferencesFoundYouCanNowDeleteThisEntity: msg("No references found. You can now delete this entity."),
    Refresh: msg("Refresh"),
    ReferencedVia: msg("Referenced via"),
    Delete: msg("Delete"),
    ErrorDetails: msg("Error details"),
    _0MoreNotVisibleForYou: msg("{0} more not visible for you"),
};

// Signum's BooleanEnum (Entities/EnumMessages.cs) — the Yes/No vocabulary a plain `boolean` is shown
// with, e.g. EnumLine's nullable-Boolean dropdown. An ENUM rather than a msg() container because the
// two member NAMES ("False"/"True") are the keys the translation files carry and `Enum.niceName`
// resolves; Signum's [Description] on each member is why the default language reads No/Yes rather
// than the humanised member name.
//
// registerEnum is hand-written: the quote-transformer only auto-registers an enum that an entity FIELD
// references, and nothing STORES a BooleanEnum. Without it the enum has no registered name, so
// `Enum.niceName` has nothing to look a translation up by — registration alone creates no table (the
// schema builder makes one only when a FieldEnum points at the enum).
export enum BooleanEnum {
    False,
    True,
}

registerEnum(BooleanEnum);

Enum.setNiceName(BooleanEnum, "False", "No");
Enum.setNiceName(BooleanEnum, "True", "Yes");

// react-widgets (Signum's ReactWidgetsMessage) — the labels and aria strings the react-widgets-up
// DropdownList / Combobox / Multiselect / DatePicker render on their own. They reach a widget through
// the `messages` prop of <Localization>, assembled by `getMessages` in client/Lines/ReactWidgetsLocalizer.
export const ReactWidgetsMessage = {
    CreateOption: msg("Create option"),
    CreateOption0: msg("Create option {0}"),
    DateButton: msg("Select date"),
    DecrementValue: msg("Decrement value"),
    EmptyFilter: msg("The filter returned no results"),
    EmptyList: msg("There are no items in this list"),
    // react-widgets-up has no filter-placeholder slot in its Messages contract, so nothing passes this
    // one on; it is declared (with Signum's own empty default) so the member keeps a home if one appears.
    FilterPlaceholder: msg(""),
    IncrementValue: msg("Increment value"),
    MoveBack: msg("Navigate back"),
    MoveForward: msg("Navigate forward"),
    MoveToday: msg("Today"),
    NoneSelected: msg("no selected items"),
    OpenCombobox: msg("open combobox"),
    RemoveLabel: msg("Remove selected item"),
    SelectedItems0: msg("Selected items: {0}"),
    TagsLabel: msg("Selected items"),
};

// Calendar (Signum's CalendarMessage) — the word "Today" on its own. The DatePicker's calendar renders
// its Today button from react-widgets' `moveToday` message, which ReactWidgetsMessage.MoveToday feeds,
// so nothing reads this container yet: it is the localized noun any other "today" affordance should
// reach for instead of inventing a second string.
export const CalendarMessage = {
    Today: msg("Today"),
};
