import { reflect, init } from "@altea/altea/data/reflection";
import { Entity, MixinEntity, type Type } from "@altea/altea/data/entity";
import { Lite } from "@altea/altea/data/lite";
import { entity, stringLengthValidator } from "@altea/altea/data/decorators";
import { MixinDeclarations } from "@altea/altea/data/mixinDeclarations";
import type { ConstructSymbol, FromMany } from "@altea/altea/data/operations";
import type { IQuery } from "@altea/altea/data/iquery";
import { ProcessAlgorithmSymbol, type IProcessDataEntity } from "@altea/altea-processes/data/Processes";
import type { ProcessEntity } from "@altea/altea-processes/data/Processes";
import { EmailMessageEntity, EmailMessageState } from "./EmailMessage";

// Port of Signum.Mailing/Package/ — the BATCH side of the module: sending one template to many targets, or
// re-sending a selection, as ONE observable process instead of N fire-and-forget sends.
//
// A package is just a name; what belongs to it is the MESSAGE, through the mixin below. Signum keeps that
// asymmetry on purpose — a package can hold hundreds of thousands of messages, so an owned collection here
// would drag them all in on every retrieve (the same reasoning PackageEntity's own header gives).
//
// altea divergences:
//  - Signum's `SendEmailTaskEntity` (a scheduled task that sends a template to a query's results) is NOT
//    ported with this: it is a separate feature on top, and no database this port has been exercised
//    against carries its table.
//  - the mixin's fields are INLINED onto email_message by altea (`package_id`), which is the column Signum's
//    mixin produces too — so a database generated by either reads the same.

/** Signum's EmailPackageEntity — a named batch, referenced by `ProcessEntity.data`. */
@reflect
@entity("System", "Transactional")
export class EmailPackageEntity extends Entity implements IProcessDataEntity {

    @stringLengthValidator({ max: 200 })
    name: string | null = null;

    /**
     * Signum's `EmailMessages()` / `RemainingMessages()` / `ExceptionMessages()` [AutoExpressionField]
     * extension methods — here `withQuoted` PROTOTYPE members the SERVER assigns (their bodies are
     * queries), which is why they are optional on this isomorphic declaration. Same idiom as
     * @altea/altea-printing's `PrintPackageEntity.lines()`.
     */
    emailMessages?(): IQuery<EmailMessageEntity>;
    remainingMessages?(): IQuery<EmailMessageEntity>;
    exceptionMessages?(): IQuery<EmailMessageEntity>;

    toString(): string {
        return `EmailPackage ${this.name ?? ""}`.trim();
    }
}

/**
 * Signum's EmailMessagePackageMixin — the message's back-pointer to its package.
 *
 * Declared on BOTH TIERS before anything is (de)serialized or the schema is built, exactly as
 * @altea/altea-diff-log's mixin is: it is what tells the serializer and the schema builder that the field
 * exists. Put the call next to the app's other entity overrides.
 */
@reflect
export class EmailMessagePackageMixin extends MixinEntity {
    package: Lite<EmailPackageEntity> | null = null;
}

export namespace EmailMessagePackageMixin {
    let declared = false;

    export function declare(): void {
        if (declared)
            return;
        declared = true;

        MixinDeclarations.register(
            EmailMessageEntity as unknown as Type<EmailMessageEntity>,
            EmailMessagePackageMixin as unknown as Type<EmailMessagePackageMixin>);
    }

    export function isDeclared(): boolean {
        return declared;
    }
}

/** Signum's `[AutoInit] EmailMessageProcess` — the two algorithms this module registers. */
export namespace EmailMessageProcess {
    /** Render a template for every line of a PackageEntity and queue each message. */
    export const CreateEmailsSendAsync: ProcessAlgorithmSymbol = init();
    /** Send every still-unsent message of an EmailPackageEntity. */
    export const SendEmails: ProcessAlgorithmSymbol = init();
}

/** Signum's `[AutoInit] EmailMessagePackageOperation`. */
export namespace EmailMessagePackageOperation {
    export const ReSendEmails: ConstructSymbol<ProcessEntity, FromMany<EmailMessageEntity>> = init();
}

